[package]
name = "prediction_real"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
ndarray-rand = "0.14.0"
ndarray-stats = "0.5.1"
csv = "1.1.7"
rand = "0.8.5"