[package]
name = "FinalProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.35.4"
plotters = "0.3.5" 
csv = "1.1.6"

